# サイトの基本情報
site_name: KCCT-ROBOTICS-WIKI
site_description: 神戸高専のオープンWIKI
site_author: miyamiyamon

# Materialテーマを使用
theme:
  name: material
  language: ja  # 日本語を指定
  palette:
    scheme: slate
    primary: pink
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono

hide:
  - navigation

# Markdown拡張機能
markdown_extensions:
  - toc:         # 目次生成
      permalink: true
  - tables       # テーブル
  - pymdownx.emoji:  # 絵文字
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight  # コードハイライト
  - pymdownx.inlinehilite
  - pymdownx.magiclink  # URLを自動リンク化
  - pymdownx.superfences  # 高度なコードフェンス

# サイト全体の設定
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/miyamiyamon/faq2answer/issues/new?assignees=&labels=&projects=KobeKosenRobotics%2F6&template=faq-form.yaml&title=%5BFAQ%5D%EF%BC%9A
    - icon: fontawesome/brands/twitter
      link: https://x.com/kcct_roboken?s=11

# 日本語フォントを表示するためのCSS設定
extra_css:
  - stylesheets/extra.css